// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Cheerio = require("cheerio");
var Cheerio$BsCheerio = require("./Cheerio.bs.js");

var html = "\n<ul>\n  <li class=\"class\">Hello</li>\n</ul>\n";

console.log(Curry._2(Cheerio$BsCheerio.select, Cheerio.load(html), "li").prop("data-x", 2));

exports.html = html;
/*  Not a pure module */
